### ISSUE TITLE
Argh!CSRF token mismatch.

### ISSUE THREAD

**Issue by jefelon** [gdarko/laravel-vue-starter#7]
Argh!CSRF token mismatch.

On register page

**Comment by gdarko** [comment]
Hey @jefelon  - I checked but can't reproduce the issue.

Few things:

1. Can be expired CSRF token, if you left the window for long period of time. Refresh should fix the issue. 
2. Check .env to see if you have APP_KEY set up

I will try to add some mechanism to handle case 1, probably refresh the page to generate new token after the one is expired.

Best Regards,
Darko

**Comment by CarstenRuetz** [comment]
Hi @jefelon and @gdarko 

Had the same issue, debugging led to checking exactly which cookies are sent with the request - there was no X-XSRF-TOKEN set in my case. 
Configuration relating to these variables needed to be fixed in my case: 

SANCTUM_STATEFUL_DOMAINS=localhost:8010
SESSION_DOMAIN=localhost

session domain without a port, but for sanctum WITH port - in my case 8010.

Maybe this helps.

**Comment by gdarko** [comment]
Thank you so much @CarstenRuetz  - I added this to the README.
